In [2]:
#numpy 

import numpy as np


print (np. identity(3))   #to print identity matrix but values are float

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [3]:
#to make value as int

In [6]:
y = np.identity(3)
print (y)
print(y.dtype)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
float64


In [7]:
x = y.astype(int)  # astype is used to convert the values
print(x)
print (x.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
int32


In [8]:
#to create a random matrix with random values from low to high

In [83]:
print (np.random.randint(5,11,size=(3,3)))

[[ 9 10 10]
 [ 6  7  5]
 [ 5 10  8]]


In [11]:
#numpy.arange

In [12]:
print(np.arange(10))  #n-1 values will be printed

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(1,11))  # this is used to include 1 and remove 11

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print (np.arange(1,21,3))  # so 3 is gap 1 is included and 21 is excluded 

[ 1  4  7 10 13 16 19]


In [16]:
print (np.arange(1,10, dtype=np.float)) # DEFAULT DATA TYPE OF INTEGER IS CHANGED TO FLOAT

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [17]:
#numpy.linspace    returns number spaces 


In [18]:
print(np.linspace(1,50,num=3))  #so interval is created at total values of 3

[  1.   25.5  50. ]


In [19]:
#numpu.indices   #tells the indedxes

In [22]:
print(np.indices((3,4)))

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [23]:
# Datatypes in numpy 

In [30]:
x = np.array ([1,2,3,4,5])
y = np.array([1.,2.,3.,4.,5.])
type(x)
print (type(x))
print("data type of x array is", x.dtype)
print("data type of y array is", y.dtype)

<class 'numpy.ndarray'>
data type of x array is int32
data type of y array is float64


In [33]:
z = np.array([1,2,3,4,5], dtype=np.float)# forcefully changinhg the value to float and for float 32 do it float32
print(z)

[ 1.  2.  3.  4.  5.]


In [34]:
#numpy. reshape

In [36]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [37]:
a.shape # means there are 6 elemnts in 1d array 

(6,)

In [38]:
#reshape function 

In [39]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
a.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a.reshape((6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
twod = np.array([[1,2,3],[4,5,6]])
print (twod)

[[1 2 3]
 [4 5 6]]


In [44]:
twod.shape

(2, 3)

In [45]:
twod.reshape((6))

array([1, 2, 3, 4, 5, 6])

In [48]:
twod.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [50]:
a = np.arange(4).reshape(2,2)
print (a)

[[0 1]
 [2 3]]


In [52]:
np.transpose(a) # makes the transpose of the array

array([[0, 2],
       [1, 3]])

In [53]:
#converting list into an array 

In [55]:
list = [10,20,30,40]
print (list)

[10, 20, 30, 40]


In [56]:
listarray = np.array(list)
print(listarray)

[10 20 30 40]


In [57]:
#slicing

In [61]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print (a[:5])
print (a[0:5])
print(a[0:6:2]) #remove every 2 elements

[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [63]:
a = np.arange(51)
print(a[0::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [66]:
import pandas as pd

In [67]:
# series

In [68]:
data = np.array([1,2,3,4,5,6])
print(data)

[1 2 3 4 5 6]


In [69]:
s = pd.Series(data)
print(s)                   # thisgives us the labelled array

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [73]:
data = np.array(['a','b','c','d','e','f'])
s = pd.Series(data)
print(s)


0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [74]:
s = pd.Series(data,index=[100,200,300,400,500,600])
print(s)

100    a
200    b
300    c
400    d
500    e
600    f
dtype: object


In [75]:
#dataframe

In [80]:
mydata = {'gender':['M','F','M'], 'emp_id':[1,2,3], 'age' :[27,22,21]}

In [81]:
df = pd.DataFrame(mydata, columns = ['emp_id', 'age', 'gender'])
print(df)

   emp_id  age gender
0       1   27      M
1       2   22      F
2       3   21      M
